USE [master]
GO

/****** Object:  Database [ySubmarine]    Script Date: 18/08/2024 13:38:46 ******/
CREATE DATABASE [ySubmarine]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ySubmarine', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ySubmarine.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ySubmarine_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ySubmarine_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ySubmarine].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ySubmarine] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ySubmarine] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ySubmarine] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ySubmarine] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ySubmarine] SET ARITHABORT OFF 
GO

ALTER DATABASE [ySubmarine] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ySubmarine] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ySubmarine] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ySubmarine] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ySubmarine] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ySubmarine] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ySubmarine] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ySubmarine] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ySubmarine] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ySubmarine] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ySubmarine] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ySubmarine] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ySubmarine] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ySubmarine] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ySubmarine] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ySubmarine] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ySubmarine] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ySubmarine] SET RECOVERY FULL 
GO

ALTER DATABASE [ySubmarine] SET  MULTI_USER 
GO

ALTER DATABASE [ySubmarine] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ySubmarine] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ySubmarine] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ySubmarine] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ySubmarine] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ySubmarine] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ySubmarine] SET QUERY_STORE = ON
GO

ALTER DATABASE [ySubmarine] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ySubmarine] SET  READ_WRITE 
GO


